language: node_js
node_js:
  - "0.10"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - bash -n install.sh
  - bash -n $(find src -type f |grep -v .txt)
  - tools/bashstyle install.sh
  - tools/bashstyle $(find src -type f | grep -v .txt)
  - bats test/bats
notifications:
  email:
    on_success: never
